### PR TITLE
New class

### PR DESCRIPTION
**Pull request by MeriAv87**
New class

### CODE REVIEW

**Review by sofiiberlin — APPROVED** [review]
I see you changes, Sofiia

**Comment by AndaKrasniqi** [comment]
Great job Meri

**Review by AndaKrasniqi — APPROVED** [review]
Great job

**Comment by Esmeralddi** [comment]
great

**Comment by Esmeralddi** [comment]
great

**Review by Esmeralddi — APPROVED** [review]

**Review by MagbuleB — APPROVED** [review]
good job

**Review by SeymAvci — APPROVED** [review]

**Review by SeymAvci — APPROVED** [review]

**Comment by GlitiaMadalin** [comment]
great

**Comment by GlitiaMadalin** [comment]
great job

**Review by GlitiaMadalin — APPROVED** [review]
Good job

**Review by GlitiaMadalin — APPROVED** [review]

**Review by GlitiaMadalin — APPROVED** [review]
Good job

**Review by MagbuleB — APPROVED** [review]
great

**Comment by GlitiaMadalin** [comment]
Good work

**Pull request merged**
